#!/usr/bin/env node
/**
 * One-time setup for building the beacon firmware.
 *
 * Downloads a portable arduino-cli, then installs the pinned ESP32 core and the
 * four libraries listed in Readme.pdf section 2. Versions are pinned so a rebuilt
 * firmware is byte-comparable with the one students are already flashing.
 *
 *   node tools/setup.mjs
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const BIN = path.join(ROOT, "tools", "bin");
const CONFIG = path.join(ROOT, "tools", "arduino-cli.yaml");

const CLI_VERSION = "1.5.1";
const CORE = "esp32:esp32@3.3.11";
const LIBS = [
  "RadioLib@7.7.1",
  "XPowersLib@0.3.1",
  "TinyGPSPlus@1.0.3",
  "ESP8266 and ESP32 OLED driver for SSD1306 displays@4.6.2",
];

const isWin = process.platform === "win32";
const cliPath = path.join(BIN, isWin ? "arduino-cli.exe" : "arduino-cli");

async function main() {
  if (!fs.existsSync(cliPath)) await downloadCli();
  else console.log(`> arduino-cli already present at ${cliPath}`);

  // build-firmware.mjs writes this too; do it here so setup works standalone.
  const sharedData = isWin
    ? path.join(process.env.LOCALAPPDATA ?? "", "Arduino15")
    : path.join(process.env.HOME ?? "", ".arduino15");
  const dataDir = fs.existsSync(sharedData) ? sharedData : path.join(ROOT, "tools", "arduino-data");
  fs.mkdirSync(dataDir, { recursive: true });
  fs.writeFileSync(
    CONFIG,
    [
      "# Generated by tools/setup.mjs — do not edit, do not commit.",
      "directories:",
      `  data: ${dataDir}`,
      `  downloads: ${path.join(dataDir, "staging")}`,
      `  user: ${path.join(ROOT, "tools", "arduino")}`,
      "library:",
      "  enable_unsafe_install: false",
      "",
    ].join("\n"),
  );

  run(["--config-file", CONFIG, "core", "update-index"]);
  run(["--config-file", CONFIG, "core", "install", CORE]);
  run(["--config-file", CONFIG, "lib", "update-index"]);
  run(["--config-file", CONFIG, "lib", "install", ...LIBS]);

  console.log("\n> setup complete. Build with:");
  console.log("    node tools/build-firmware.mjs          # T-Beam beacon");
  console.log("    node tools/build-firmware.mjs s3-test  # ESP32-S3 pipeline probe");
}

function run(args) {
  console.log(`> arduino-cli ${args.slice(2).join(" ")}`);
  execFileSync(cliPath, args, { stdio: "inherit" });
}

async function downloadCli() {
  const asset = isWin
    ? "Windows_64bit.zip"
    : process.platform === "darwin"
      ? process.arch === "arm64" ? "macOS_ARM64.tar.gz" : "macOS_64bit.tar.gz"
      : process.arch === "arm64" ? "Linux_ARM64.tar.gz" : "Linux_64bit.tar.gz";

  const url = `https://github.com/arduino/arduino-cli/releases/download/v${CLI_VERSION}/arduino-cli_${CLI_VERSION}_${asset}`;
  console.log(`> downloading ${url}`);

  fs.mkdirSync(BIN, { recursive: true });
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download failed: HTTP ${res.status}`);
  const archive = path.join(BIN, asset);
  fs.writeFileSync(archive, Buffer.from(await res.arrayBuffer()));

  if (asset.endsWith(".zip")) {
    // tar is present on Windows 10+ and handles zip.
    execFileSync("tar", ["-xf", archive, "-C", BIN], { stdio: "inherit" });
  } else {
    execFileSync("tar", ["-xzf", archive, "-C", BIN], { stdio: "inherit" });
  }
  fs.rmSync(archive);
  if (!isWin) fs.chmodSync(cliPath, 0o755);
  console.log(`> installed ${cliPath}`);
}

main().catch((e) => {
  console.error(e.message ?? e);
  process.exit(1);
});
